EXTRA_DIST += \
 tests/comparison.sh \
 tests/spintest-eventual.sh \
 tests/spintest-threadjoin.sh \
 tests/spintest-suspend.sh \
 tests/spintest-mutex.sh \
 tests/spintest-barrier.sh \
 tests/spintest-cond.sh 

TESTS += \
 tests/comparison.sh \
 tests/spintest-eventual.sh \
 tests/spintest-threadjoin.sh \
 tests/spintest-suspend.sh \
 tests/spintest-mutex.sh \
 tests/spintest-barrier.sh \
 tests/spintest-cond.sh 

check_PROGRAMS += \
 tests/spintest-eventual \
 tests/spintest-threadjoin \
 tests/spintest-suspend \
 tests/spintest-mutex \
 tests/spintest-barrier \
 tests/spintest-cond

